sudo: required
dist: trusty
language: python
matrix:
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytest h5py
  - source activate test-environment
  - pip install pytest-pep8
  # install PIL for preprocessing tests
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install Pillow;
    fi

  - pip install -e .[tests]

  # install TensorFlow
  - conda install tensorflow

# command to run tests
script:
  # create dataset directory to avoid concurrent directory creation at runtime
  - mkdir ~/.keras/datasets

  # Run tests
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
       PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8;
    else
       PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;
    fi
after_success:
  - coveralls
